# Generated by Django 2.0 on 2019-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190817_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('adder', models.CharField(max_length=25, null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('hobby', models.CharField(max_length=22, null=True)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
